export const environment = {
  production: false,
  oauthToken: "Bearer BQBhkzhQvCXltpHrgYVdWSSZJfcBTvgKk0cnmGxC3Xw4j5oXYf_ZKNfngfp_Q8PEUiJLJoASfsl6eSkWgk83GsIt5k66irSkbBwQySN6FcrMF2JHSD43AFXEVyiI4Vt6wnFpErTv6NCC4e4hTjhWdl5q8rAw2oFuq5VUwp_AreXt"
};
